---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kargo-repo-auth
  namespace: {{ .Values.appName }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: kargo-repo-auth
    creationPolicy: Owner
    template:
      metadata:
        labels:
          kargo.akuity.io/cred-type: git
  dataFrom:
    - extract:
        key: {{ .Values.onepassword.gitItem }}
