---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: kargo-repo-auth
  namespace: {{ .Values.appName }}
  labels:
    kargo.akuity.io/cred-type: git
spec:
  itemPath: {{ .Values.onepassword.gitItemPath }}
