---
apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.appName }}
spec:
  promotionPolicies:
    - stageSelector:
        name: dev
      autoPromotionEnabled: true
