---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/dyegoe/homelab.git
        revision: main
        files:
          - path: apps/*/config.json
  template:
    metadata:
      name: "{{.appName}}"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: "{{ if index . `argocdProject` }}{{ index . `argocdProject` }}{{ else }}apps{{ end }}"
      source:
        repoURL: https://github.com/dyegoe/homelab.git
        path: charts/tenant
        targetRevision: main
        helm:
          releaseName: "{{.appName}}"
          valuesObject:
            appName: "{{.appName}}"
            repoURL: "{{.repoURL}}"
            imageURL: "{{.imageURL}}"
            argocdProject: "{{ if index . `argocdProject` }}{{ index . `argocdProject` }}{{ end }}"
            onepassword:
              gitItemPath: "{{.onepassword.gitItemPath}}"
              imageItemPath: "{{ if index .onepassword `imageItemPath` }}{{ index .onepassword `imageItemPath` }}{{ end }}"
              argocdRepoItemPath: "{{ if index .onepassword `argocdRepoItemPath` }}{{ index .onepassword `argocdRepoItemPath` }}{{ end }}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{.appName}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ServerSideApply=true
          - CreateNamespace=false # We don't want ArgoCD to create the namespace, as Kargo will manage it as part of Project.
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
