---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - clusterissuer-letsencrypt-cloudflare-prod.yaml
  - clusterissuer-letsencrypt-cloudflare-staging.yaml
  - onepassword-cloudflare-api-token.yaml
