---
reloader:
  podMonitor:
    enabled: true
    interval: 30s
  deployment:
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi
