---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubevirt
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: addons
  source:
    repoURL: https://github.com/dyegoe/homelab.git
    targetRevision: main
    path: addons/kubevirt
  destination:
    server: https://kubernetes.default.svc
    namespace: kubevirt
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/conversion/webhook/clientConfig/caBundle
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: cdis.cdi.kubevirt.io
      jsonPointers:
        - /spec/versions
