---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gateway-crds.yaml
  - snapshot-crds.yaml
  - prometheus-operator-crds.yaml
  - cilium.yaml
  - sealed-secrets.yaml
  - metrics-server.yaml
  - kubelet-serving-cert-approver.yaml
  - external-secrets.yaml
  - reloader.yaml
  - cert-manager.yaml
  - external-dns.yaml
  - gateway.yaml
  - cloudflared.yaml
  - longhorn.yaml
  - kube-prometheus-stack.yaml
  - loki.yaml
  - alloy.yaml
  - kargo.yaml
