---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: snapshot-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-8"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: addons
  source:
    repoURL: https://github.com/kubernetes-csi/external-snapshotter
    path: client/config/crd
    targetRevision: v8.6.0
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - ClientSideApplyMigration=false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
