---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kargo-admin
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: kargo-admin
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: homelab-kargo-admin
