---
provider: cloudflare
domainFilters:
  - nodes.ee
policy: sync
sources:
  - service
  - ingress
  - gateway-httproute
  - gateway-grpcroute
serviceMonitor:
  enabled: true
  interval: 30s
env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-api-token
        key: credential
