{
 "title": "Alloy Resources",
 "tags": [
  "alloy",
  "monitoring",
  "prometheus"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "pod",
    "query": "label_values(alloy_build_info, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU usage",
   "type": "timeseries",
   "description": "CPU usage of the Alloy process relative to 1 CPU core.\n\nFor example, 100% means using one entire CPU core.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(alloy_resources_process_cpu_seconds_total{pod=~\"$pod\"}[$__rate_interval]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory (RSS)",
   "type": "timeseries",
   "description": "Resident memory size of the Alloy process.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (alloy_resources_process_resident_memory_bytes{pod=~\"$pod\"})\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Garbage collections",
   "type": "timeseries",
   "description": "Rate at which the Alloy process performs garbage collections.\n",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(pod) (\n  rate(go_gc_duration_seconds_count{pod=~\"$pod\"}[5m])\n  and on(instance)\n  alloy_build_info{pod=~\"$pod\"}\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "description": "Number of goroutines which are running in parallel. An infinitely\ngrowing number of these indicates a goroutine leak.\n",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(pod) (\n  go_goroutines{pod=~\"$pod\"}\n  and on(instance)\n  alloy_build_info{pod=~\"$pod\"}\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory (heap in use)",
   "type": "timeseries",
   "description": "Heap memory currently in use by the Alloy process.\n",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (\n  go_memstats_heap_inuse_bytes{pod=~\"$pod\"}\n  and on(instance)\n  alloy_build_info{pod=~\"$pod\"}\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network receive bandwidth",
   "type": "timeseries",
   "description": "Rate of data received across all network interfaces for the machine\nAlloy is running on.\n\nData shown here is across all running processes and not exclusive to\nthe running Alloy process.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(alloy_resources_machine_rx_bytes_total{pod=~\"$pod\"}[$__rate_interval]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network send bandwidth",
   "type": "timeseries",
   "description": "Rate of data sent across all network interfaces for the machine\nAlloy is running on.\n\nData shown here is across all running processes and not exclusive to\nthe running Alloy process.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(alloy_resources_machine_tx_bytes_total{pod=~\"$pod\"}[$__rate_interval]))\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}