{
 "title": "Alloy Controller",
 "tags": [
  "alloy",
  "monitoring",
  "prometheus"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "pod",
    "query": "label_values(alloy_build_info, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Running instances",
   "type": "stat",
   "description": "The number of Alloy instances whose metrics are being sent and reported.\n",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "instances" } },
   "targets": [
    {
     "expr": "count(group(alloy_component_controller_running_components{}) by (instance))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running components",
   "type": "stat",
   "description": "The number of running components across all running instances.\n",
   "gridPos": { "h": 4, "w": 10, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "components" } },
   "targets": [
    {
     "expr": "sum(alloy_component_controller_running_components{})\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overall component health",
   "type": "stat",
   "description": "The percentage of components which are in a healthy state.\n",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(alloy_component_controller_running_components{health_type=\"healthy\"}) /\nsum(alloy_component_controller_running_components{})\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Components by health",
   "type": "bargauge",
   "description": "Breakdown of components by health across all running instances.\n\n* Healthy: components have been evaluated completely and are reporting themselves as healthy.\n* Unhealthy: Components either could not be evaluated or are reporting themselves as unhealthy.\n* Unknown: A component has been created but has not yet been started.\n* Exited: A component has exited. It will not return to the running state.\n\nMore information on a component's health state can be retrieved using\nthe Alloy UI.\n\nNote that components may be in a degraded state even if they report\nthemselves as healthy. Use component-specific dashboards and alerts\nto observe detailed information about the behavior of a component.\n",
   "gridPos": { "h": 12, "w": 14, "x": 10, "y": 4 },
   "targets": [
    {
     "expr": "sum(alloy_component_controller_running_components{health_type=\"healthy\"}) or vector(0)\n",
     "legendFormat": "Healthy"
    },
    {
     "expr": "sum(alloy_component_controller_running_components{health_type=\"unhealthy\"}) or vector(0)\n",
     "legendFormat": "Unhealthy"
    },
    {
     "expr": "sum(alloy_component_controller_running_components{health_type=\"unknown\"}) or vector(0)\n",
     "legendFormat": "Unknown"
    },
    {
     "expr": "sum(alloy_component_controller_running_components{health_type=\"exited\"}) or vector(0)\n",
     "legendFormat": "Exited"
    }
   ]
  },
  {
   "title": "Component evaluation rate",
   "type": "timeseries",
   "description": "The frequency at which components get updated.\n",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(alloy_component_evaluation_seconds_count{}[$__rate_interval]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Component evaluation time",
   "type": "timeseries",
   "description": "The percentiles for how long it takes to complete component evaluations.\n\nComponent evaluations must complete for components to have the latest\narguments. The longer the evaluations take, the slower it will be to\nreconcile the state of components.\n\nIf evaluation is taking too long, consider sharding your components to\ndeal with smaller amounts of data and reuse data as much as possible.\n",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(alloy_component_evaluation_seconds{}[$__rate_interval])))\nor\nhistogram_quantile(0.99, sum by (le) (rate(alloy_component_evaluation_seconds_bucket{}[$__rate_interval])))\n",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(alloy_component_evaluation_seconds{}[$__rate_interval])))\nor\nhistogram_quantile(0.50, sum by (le) (rate(alloy_component_evaluation_seconds_bucket{}[$__rate_interval])))\n",
     "legendFormat": "50th percentile"
    },
    {
     "expr": "(\n  histogram_sum(sum(rate(alloy_component_evaluation_seconds{}[$__rate_interval]))) /\n  histogram_count(sum(rate(alloy_component_evaluation_seconds{}[$__rate_interval])))\n)\nor\n(\n  sum(rate(alloy_component_evaluation_seconds_sum{}[$__rate_interval])) /\n  sum(rate(alloy_component_evaluation_seconds_count{}[$__rate_interval]))\n)\n",
     "legendFormat": "Average"
    }
   ]
  }
 ]
}