---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: repo-gh-dyegoe-homelab
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: repo-gh-dyegoe-homelab
    creationPolicy: Owner
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
  dataFrom:
    - extract:
        key: homelab-gh-pat-argocd-homelab
