---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: repo-homelab-token
  labels:
    argocd.argoproj.io/secret-type: repository
spec:
  itemPath: "vaults/Kubernetes/items/homelab-argocd-github-personal-access-token"
