{
 "title": "Cilium Operator",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage per node",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "min(irate(cilium_operator_process_cpu_seconds_total{io_cilium_app=\"operator\"}[1m])) by (pod) * 100",
     "legendFormat": "min"
    },
    {
     "expr": "avg(irate(cilium_operator_process_cpu_seconds_total{io_cilium_app=\"operator\"}[1m])) by (pod) * 100",
     "legendFormat": "avg"
    },
    {
     "expr": "max(irate(cilium_operator_process_cpu_seconds_total{io_cilium_app=\"operator\"}[1m])) by (pod) * 100",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Resident memory status",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(cilium_operator_process_resident_memory_bytes{io_cilium_app=\"operator\"})",
     "legendFormat": "AVG_resident_memory_bytes"
    },
    {
     "expr": "max(cilium_operator_process_resident_memory_bytes{io_cilium_app=\"operator\"})",
     "legendFormat": "MAX_resident_memory_bytes_max"
    },
    {
     "expr": "min(cilium_operator_process_resident_memory_bytes{io_cilium_app=\"operator\"})",
     "legendFormat": "MIN_resident_memory_bytes_min"
    }
   ]
  },
  { "title": "IPAM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Metadata Resync Operations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(cilium_operator_ipam_resync_total[1m])",
     "legendFormat": "operations"
    }
   ]
  }
 ]
}