---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: telegram-bot-token
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: telegram-bot-token
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: homelab-telegram-bot-token
