---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - httproute-grafana.yaml
  - httproute-grafana-redirect.yaml
  - httproute-prometheus.yaml
  - httproute-prometheus-redirect.yaml
  - externalsecret-telegram-bot-token.yaml
