---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: onepassword
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://1password.github.io/connect-helm-charts
      chart: connect
      targetRevision: 2.4.1
      helm:
        releaseName: onepassword
        valueFiles:
          - $values/apps/onepassword/helm/values.yaml
    # Source to provide references for Helm values
    - repoURL: https://github.com/dyegoe/homelab.git
      targetRevision: main
      ref: values
    # Source to provide references for Kustomize bases
    - repoURL: https://github.com/dyegoe/homelab.git
      targetRevision: main
      path: apps/onepassword
  destination:
    server: https://kubernetes.default.svc
    namespace: onepassword
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
