---
resources:
  requests:
    cpu: 50m
    memory: 200Mi
  limits:
    cpu: 200m
    memory: 400Mi
replicas: 2
podDisruptionBudget:
  enabled: true
  minAvailable: 1
securityContext:
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - metrics-server
          topologyKey: kubernetes.io/hostname
