---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: repo-gh-dyegoe-website
  labels:
    kargo.akuity.io/cred-type: git
spec:
  itemPath: "vaults/Kubernetes/items/homelab-gh-pat-kargo-website"
